### ISSUE TITLE
Add Additional Commands

### ISSUE THREAD

**Issue by OwenArnold** [DMSC-Instrument-Data/instrument-prototype#26]
From @SimonHeybrock:
As just discussed on the whiteboard, we can test the other extreme of having a different parameters for every child component:

```
void CompositeComponent::shiftChildPositionsBy(const std::vector<Vector3d> &deltas) {
  for (size_t i = 0; i < m_children.size(); ++i) {
     m_children[i]->shiftPositionBy(deltas[i]);
   }
}
```

Same for rotations.
We should add benchmarks for these.

**Comment by OwenArnold** [comment]
@SimonHeybrock. My memory isn't great on this one - why were we intending to write a benchmark for this. You get the advantage of having a single `Command` hence one cow to the bank. Was that the reason for adding new command + the benchmark?

**Comment by SimonHeybrock** [comment]
@OwenArnold I think the point was that in this case we will need to initialize the rotation matrix N times instead of just once. This implies that there should be a higher cost (more floating-point operations), i.e., more work done by `Eigen`, which we might also want to compare to what is done in Mantid.

We need a *separate* command for this since we do not want to use N commands, which would be very inefficient.

**Comment by OwenArnold** [comment]
Commands are not required any longer
